### ISSUE TITLE
plans for extending it for rails 4+

### ISSUE THREAD

**Issue by r3bo0t** [tcopeland/filter_decrufter#1]
First of all nice small but quite a utility specially for large/long running projects. Technically its not an issue, just had one question.

`Are you planning to extend this utility to support rails ~ 4.x as well?`

**Comment by tcopeland** [comment]
Thanks @conflikt !   And sorry, I just updated docs, I tested it with 4.0 and 4.2 and it worked fine in both.  Haven't tried it with 4.1 yet tho.

**Comment by r3bo0t** [comment]
Actually after briefly looking into the codebase, I noticed your Checker class checking for [before|after|around]_filter methods but with new norms, `before_action, after_action & around_action` I doubt it will be working the same way, UNLESS I missed something big time.

**Comment by tcopeland** [comment]
Whoa, you're undoubtedly correct... I'll have add support for that, thanks!

**Comment by tcopeland** [comment]
v0.0.4 released with support for before/after/around_action, thanks!
